### ISSUE TITLE
Create selection screen

### ISSUE THREAD

**Issue by jacquelinehuang** [ucsb-cs48-w19/5pm-pet-life#14]
Create screen where user can pick between one of two pets, a cat and a dog. 

- The user should be able to easily click or tap on the image of the pet to select. 
- Maybe also add a confirm popup just in case?

**Comment by weiqingqi** [comment]
we might consider adding an option that allow users to go back to the previous step.

**Comment by chenyinluo** [comment]
will the user be able to choose the color?
